export interface Message {
  id: string;
  role: "user" | "opponent";
  content: string;
  isQuickAction?: boolean;
  /** Present on opponent messages from debate mode — which persona spoke (stable avatars in transcript). */
  personaId?: string;
}

export interface DebateSetup {
  template: string;
  topic: string;
  position: string;
  context: string;
  lens: "investor" | "customer" | "competitor" | "postmortem" | "market" | "future";
}

/** Heuristic vertical (tech, fintech, …) for imagery and prompts; optional on older sessions */
export interface IdeaCategoryRef {
  id: string;
  label: string;
}

/** Dual-model score reconciliation (GPT-4.1 primary + Gemini blind scorer) */
export interface ScoreReconciliation {
  final: Record<string, number>;
  primary: Record<string, number>;
  blind: Record<string, number>;
  deltas: Record<string, number>;
  confidence: "high" | "medium" | "low";
  maxDelta: number;
}

export interface ValidationSession {
  setup: DebateSetup;
  validationContent: string;
  messages: Message[];
  createdAt: number;
  ideaCategory?: IdeaCategoryRef;
  /** Isolated validation interview threads per persona (replaces one long debate transcript). */
  interviewChats?: Partial<Record<string, Message[]>>;
  /** Dual-model score reconciliation — present when Gemini blind scorer succeeds */
  scoreReconciliation?: ScoreReconciliation;
  /** Structured dashboard data (AI-generated alongside markdown) — drives all results charts */
  dashboardData?: DashboardData;
}

/**
 * Structured payload that powers every chart/section on /results.
 * Generated by /api/dashboard-data from the idea + validation markdown so each
 * idea produces unique, fully-populated visuals (no static placeholders).
 */
export interface DashboardData {
  score: number;
  verdict: "GO" | "CAUTION" | "NO-GO";
  confidenceLabel: "HIGH" | "MED" | "LOW";
  confidencePct: number;
  rankLabel: string;
  oneLineThesis: string;
  scoreHeroBlurb: string;
  scoreHistory: { v: string; score: number }[];
  categoryScores: {
    problemSolutionFit: number;
    marketOpportunity: number;
    competitiveEdge: number;
    businessModel: number;
    teamExecution: number;
    timingTrends: number;
  };
  /** The 6 weighted rubric rows that compose the headline score, with reasoning per row. */
  rubricBreakdown: {
    key: string;
    label: string;
    weight: number;       // weight % (sums to 100)
    score: number;        // 0-100
    contribution: number; // (score * weight) / 100, rounded to 1dp
    reason: string;       // ≤18-word justification
  }[];
  market: {
    tam: string; sam: string; som: string;
    cagrPct: number;
    intro: string;
    growth: { year: string; tam: number; sam: number; som: number }[];
    signals: { tag: string; label: string; weight: string }[];
  };
  risk: {
    intro: string;
    radar: { dim: string; value: number; full: number }[];
    breakdown: { category: string; severity: "HIGH" | "MED" | "LOW"; title: string; mitigation: string }[];
  };
  competition: {
    intro: string;
    competitors: { name: string; focus: string; price: string; traction: number; weakness: string; url?: string }[];
    scatter: { x: number; y: number; name: string; you?: boolean }[];
  };
  revenue: {
    headline: string;
    narrative: string;
    projection: { year: string; total: number; base?: number; expansion?: number }[];
    pricingModels: { plan: string; price: string; terms: string }[];
  };
  audience: {
    intro: string;
    segments: { name: string; value: number; color: string }[];
    personas: { title: string; org: string; budget: string; pain: string; why: string }[];
  };
  swot: {
    strengths: string[];
    weaknesses: string[];
    opportunities: string[];
    threats: string[];
  };
  recommendations: {
    priority: "P0" | "P1" | "P2";
    title: string;
    impact: string;
    horizon: string;
    tags: string[];
  }[];
  personaVerdicts: {
    name: string;
    role: string;
    accent: string;
    verdict: string;
    score: number;
    quote: string;
  }[];
  ticker: string[];
}

export const SESSION_KEY = "priority-debater-session";
