import { motion } from "framer-motion";
import { toast } from "sonner";
import { ArrowRight, Film, Clapperboard, Sparkles, Target, Wallet, Play } from "lucide-react";
import { FlowNav } from "@/components/flow/FlowNav";
import { TickerBar } from "@/components/flow/TickerBar";
import { CopyButton } from "@/components/flow/CopyButton";
import { Footer } from "@/components/landing/Footer";
import { CAMPAIGN } from "@/lib/flowData";
import { reveal, viewport } from "@/components/landing/anim";

const Label = ({ children }) => (
  <span className="font-mono text-[10px] uppercase tracking-[0.25em] text-black/40">{children}</span>
);
const Card = ({ children, className = "" }) => (
  <div className={`bg-white border-[1.5px] border-black shadow-hard-sm p-6 ${className}`}>{children}</div>
);

const scriptToText = (ad) =>
  `${ad.concept} — ${ad.platform} (${ad.format}, ${ad.duration}, ${ad.aspect})\nHook: ${ad.hook}\n\n` +
  ad.scenes.map((s) => `[${s.t}] ${s.visual}\n${s.line}`).join("\n\n") +
  `\n\nAd copy:\n${ad.adCopy.headline}\n${ad.adCopy.primary}`;

// aspect → preview frame size classes
const frameClass = (aspect) =>
  aspect === "9:16" ? "w-12 h-20" : aspect === "1:1" ? "w-16 h-16" : "w-24 h-[54px]";

export default function Campaign() {
  const fire = (msg, desc) => toast(msg, { description: desc });

  return (
    <div data-testid="campaign-page" className="bg-[#f4f4f0] min-h-screen">
      <FlowNav current="campaign" subtitle="v1.0 / 2026 — Video Ads" />

      {/* Hero */}
      <section className="bg-[#0a0a0a] grid-bg-dark text-white py-16 lg:py-20 border-b-[1.5px] border-black">
        <div className="max-w-[1400px] mx-auto px-5 lg:px-8 grid lg:grid-cols-12 gap-10 items-end">
          <div className="lg:col-span-8">
            <span className="font-mono text-[10px] uppercase tracking-[0.25em] text-white/40">
              Stage 06 / Video Ad Campaign — generated by AI
            </span>
            <h1 className="mt-4 font-display text-4xl sm:text-5xl lg:text-6xl uppercase leading-[0.92]">
              Don&apos;t just post.{" "}
              <span className="bg-[#ff3b30] text-white px-2">run ads that sell.</span>
            </h1>
            <p className="mt-5 max-w-2xl text-white/60 font-body leading-relaxed">
              Scroll-stopping video ads, scripted and storyboarded for each platform — from your
              idea. Generate the cuts, or hand the scripts to an editor and launch them yourself.
            </p>
            <div className="mt-6 border border-white/20 p-4 max-w-2xl">
              <Label><span className="text-white/40">Objective</span></Label>
              <p className="mt-2 font-body text-white/85">{CAMPAIGN.objective}</p>
              <div className="mt-3 pt-3 border-t border-white/10">
                <Label><span className="text-[#ffd60a]">The angle</span></Label>
                <p className="mt-2 font-body text-sm text-white/70 leading-relaxed">{CAMPAIGN.angle}</p>
              </div>
            </div>
          </div>
          <div className="lg:col-span-4 grid grid-cols-2 gap-3">
            {CAMPAIGN.kpis.map((m) => (
              <div key={m.k} className="border border-white/20 p-3">
                <p className="font-mono text-[9px] uppercase tracking-[0.18em] text-white/40">{m.k}</p>
                <p className="font-display text-3xl mt-1" style={{ color: m.c }}>{m.v}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <main className="max-w-[1400px] mx-auto px-5 lg:px-8 py-16 lg:py-20 space-y-10">
        {/* Budget & targeting */}
        <motion.section initial="hidden" whileInView="show" viewport={viewport} variants={reveal}>
          <Label>§01 / Budget &amp; targeting</Label>
          <div className="mt-4 grid lg:grid-cols-12 gap-6">
            <Card className="lg:col-span-7">
              <div className="flex items-center gap-2 mb-4">
                <Wallet size={16} />
                <span className="font-mono text-[10px] uppercase tracking-[0.18em] text-black/40">
                  {CAMPAIGN.budget.total} test · {CAMPAIGN.budget.daily} · {CAMPAIGN.budget.window}
                </span>
              </div>
              <div className="space-y-3">
                {CAMPAIGN.budgetSplit.map((b) => (
                  <div key={b.platform}>
                    <div className="flex items-center justify-between font-mono text-[11px] uppercase tracking-[0.12em] mb-1">
                      <span className="font-bold">{b.platform}</span>
                      <span className="text-black/50">{b.amount} · {b.pct}%</span>
                    </div>
                    <div className="h-3 bg-black/5 border border-black/15">
                      <div className="h-full" style={{ width: `${b.pct}%`, background: b.color }} />
                    </div>
                  </div>
                ))}
              </div>
            </Card>
            <Card className="lg:col-span-5">
              <div className="flex items-center gap-2 mb-3">
                <Target size={16} className="text-[#ff3b30]" />
                <span className="font-mono text-[10px] uppercase tracking-[0.18em] text-black/40">Audience</span>
              </div>
              <p className="text-sm text-black/70 font-body leading-relaxed">{CAMPAIGN.audience}</p>
            </Card>
          </div>
        </motion.section>

        {/* Ad concepts */}
        <motion.section initial="hidden" whileInView="show" viewport={viewport} variants={reveal}>
          <div className="flex items-center justify-between flex-wrap gap-2">
            <Label>§02 / Ad concepts — script + storyboard</Label>
            <span className="font-mono text-[10px] uppercase tracking-[0.15em] text-black/40 flex items-center gap-1.5">
              <Film size={13} /> 4 cuts, one per placement
            </span>
          </div>

          <div className="mt-4 space-y-5">
            {CAMPAIGN.ads.map((ad, i) => (
              <div key={ad.id} data-testid={`ad-card-${i}`} className="bg-white border-[1.5px] border-black shadow-hard-sm">
                {/* head */}
                <div className="flex items-center justify-between gap-4 flex-wrap px-5 py-3 border-b-[1.5px] border-black">
                  <div className="flex items-center gap-3">
                    <span className="font-mono text-[10px] uppercase tracking-[0.12em] px-2 py-1 text-white" style={{ background: ad.color }}>
                      {ad.platform}
                    </span>
                    <span className="font-display text-xl uppercase tracking-tight">{ad.concept}</span>
                  </div>
                  <div className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.12em] text-black/45">
                    <span className="border border-black/20 px-2 py-1">{ad.format}</span>
                    <span className="border border-black/20 px-2 py-1">{ad.duration}</span>
                    <span className="border border-black/20 px-2 py-1">{ad.aspect}</span>
                  </div>
                </div>

                <div className="grid lg:grid-cols-12 gap-0">
                  {/* script */}
                  <div className="lg:col-span-7 p-5 lg:border-r-[1.5px] border-black">
                    <div className="flex items-center justify-between mb-3">
                      <span className="font-mono text-[10px] uppercase tracking-[0.18em] text-[#ff3b30]">Hook</span>
                      <CopyButton text={scriptToText(ad)} label="Copy script" testid={`copy-script-${i}`} />
                    </div>
                    <p className="font-body font-bold text-base leading-snug">{ad.hook}</p>

                    <div className="mt-4 space-y-3">
                      {ad.scenes.map((s, si) => (
                        <div key={si} className="flex gap-3 border-l-2 border-black/15 pl-3">
                          <span className="font-mono text-[10px] text-black/40 w-9 shrink-0 pt-0.5">{s.t}</span>
                          <div>
                            <p className="font-mono text-[10px] uppercase tracking-[0.1em] text-black/45">{s.visual}</p>
                            <p className="text-sm text-black/80 font-body leading-snug mt-0.5">{s.line}</p>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>

                  {/* storyboard + ad copy */}
                  <div className="lg:col-span-5 p-5 bg-[#f4f4f0]">
                    <span className="font-mono text-[10px] uppercase tracking-[0.18em] text-black/40 flex items-center gap-1.5">
                      <Clapperboard size={13} /> Storyboard
                    </span>
                    <div className="mt-3 flex gap-2 flex-wrap">
                      {ad.scenes.map((s, si) => (
                        <div key={si} className={`${frameClass(ad.aspect)} bg-black text-white border border-black relative grid place-items-center`}>
                          <Play size={14} className="opacity-40" />
                          <span className="absolute top-0.5 left-0.5 font-mono text-[7px] text-white/60">{s.t}</span>
                        </div>
                      ))}
                    </div>

                    <div className="mt-4 border border-black/15 bg-white p-3">
                      <div className="flex items-center justify-between mb-1.5">
                        <span className="font-mono text-[9px] uppercase tracking-[0.18em] text-black/40">Ad copy</span>
                        <CopyButton text={`${ad.adCopy.headline}\n${ad.adCopy.primary}`} testid={`copy-adcopy-${i}`} />
                      </div>
                      <p className="font-body font-bold text-sm">{ad.adCopy.headline}</p>
                      <p className="text-xs text-black/60 font-body mt-1 leading-relaxed">{ad.adCopy.primary}</p>
                      <span className="inline-block mt-2 font-mono text-[9px] uppercase tracking-[0.12em] bg-black text-white px-2 py-1">
                        {ad.cta} →
                      </span>
                    </div>

                    <div className="mt-3 grid grid-cols-2 gap-2">
                      <button
                        onClick={() => fire("AI video generation is a demo", "Wire a text-to-video model to render this cut automatically.")}
                        data-testid={`generate-video-${i}`}
                        className="inline-flex items-center justify-center gap-1.5 font-mono text-[10px] uppercase tracking-[0.12em] bg-[#ff3b30] text-white px-2.5 py-2 hover:bg-black transition-colors"
                      >
                        <Sparkles size={12} /> Generate
                      </button>
                      <button
                        onClick={() => fire(`${ad.platform} ad launch is a demo`, "Connect your ad account to publish this creative.")}
                        data-testid={`launch-ad-${i}`}
                        className="inline-flex items-center justify-center gap-1.5 font-mono text-[10px] uppercase tracking-[0.12em] bg-black text-white px-2.5 py-2 hover:bg-[#0a66c2] transition-colors"
                      >
                        <Play size={12} /> Launch ad
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </motion.section>

        {/* Ad accounts */}
        <motion.section initial="hidden" whileInView="show" viewport={viewport} variants={reveal}>
          <Label>§03 / Connect ad accounts</Label>
          <Card className="mt-4">
            <p className="text-sm text-black/65 font-body leading-relaxed max-w-2xl">
              Connect a platform to push these creatives, set the budget split, and launch the
              test in one click — or export the scripts and run them manually.
            </p>
            <div className="mt-5 grid sm:grid-cols-2 lg:grid-cols-4 gap-3">
              {CAMPAIGN.adAccounts.map((a) => (
                <button
                  key={a.name}
                  onClick={() => fire(`${a.name} is a demo`, "OAuth + ad API wiring needed to launch live campaigns.")}
                  data-testid={`connect-${a.name.split(" ")[0].toLowerCase()}`}
                  className="flex items-center justify-between border-[1.5px] border-black p-3 hover:bg-black hover:text-white transition-colors group"
                >
                  <span className="flex items-center gap-2 font-body font-bold text-sm">
                    <span className="w-2.5 h-2.5" style={{ background: a.color }} />
                    {a.name}
                  </span>
                  <span className="font-mono text-[10px] uppercase tracking-[0.15em] text-black/40 group-hover:text-white/70">
                    Connect →
                  </span>
                </button>
              ))}
            </div>
          </Card>
        </motion.section>

        {/* CTA */}
        <motion.div
          initial="hidden"
          whileInView="show"
          viewport={viewport}
          variants={reveal}
          className="bg-black text-white border-[1.5px] border-black p-8 flex flex-col sm:flex-row items-center justify-between gap-6"
        >
          <div>
            <h2 className="font-display text-3xl sm:text-4xl uppercase leading-none">
              The ad does its job. Where does the click go?
            </h2>
            <p className="mt-2 text-white/50 font-body text-sm">
              Every cut drives to one page. Let&apos;s generate the conversion page next.
            </p>
          </div>
          <a
            href="/landing-builder"
            data-testid="campaign-to-landing-cta"
            className="group shrink-0 inline-flex items-center gap-2 bg-[#ff3b30] text-white font-mono text-xs uppercase tracking-[0.2em] px-7 py-4 border-[1.5px] border-white hover:bg-white hover:text-black transition-colors"
          >
            Generate the landing page
            <ArrowRight size={16} className="group-hover:translate-x-1 transition-transform" />
          </a>
        </motion.div>
      </main>

      <TickerBar reverse />
      <Footer />
    </div>
  );
}
