/**
 * Artifact generators — the hands-on payoff.
 *
 * Each function turns the merchant's REAL store profile (and real Shopify
 * products when available) into a finished, installable asset: the file or
 * snippet a small-business owner needs to become visible and recommendable to AI
 * shopping agents. No API key, no AI tokens — pure templating over real data, so
 * it works today and the owner can copy/download and ship it.
 */

import type { StoreProfile } from "@/lib/commerce/store-profile";
import type { ShopProduct } from "@/lib/commerce/shopify";

export interface GeneratedArtifact {
  id: string;
  title: string;
  filename: string;
  lang: "markdown" | "json" | "text" | "html";
  /** "file" installs on the store; "outreach" is an off-site action asset. */
  kind?: "file" | "outreach";
  /** One line on why this moves the needle for AI discovery. */
  why: string;
  /** Already detected on the live store. */
  present: boolean;
  /** Built from the merchant's real catalogue/identity (vs an editable template). */
  real: boolean;
  installShopify: string;
  installGeneric: string;
  content: string;
}

const jsonLd = (obj: unknown) =>
  `<script type="application/ld+json">\n${JSON.stringify(obj, null, 2)}\n</script>`;

function availabilityUrl(available: boolean) {
  return available ? "https://schema.org/InStock" : "https://schema.org/OutOfStock";
}

/* ---------------- llms.txt ---------------- */

function llmsTxt(p: StoreProfile, products: ShopProduct[]): string {
  const lines: string[] = [];
  lines.push(`# ${p.name}`);
  lines.push("");
  lines.push(`> ${p.description || `${p.name} — ${p.category}.`}`);
  lines.push("");
  lines.push(
    `${p.name} is an online store selling ${p.category}. This file helps AI assistants and shopping agents understand, cite, and recommend our products.`,
  );
  lines.push("");
  if (products.length) {
    lines.push("## Products");
    for (const pr of products.slice(0, 12)) {
      const price = `${p.currency} ${pr.price}`;
      const desc = pr.description ? ` — ${pr.description.slice(0, 120)}` : "";
      lines.push(`- [${pr.title}](${pr.url}): ${price}${desc}`);
    }
    if (products.length > 12) lines.push(`- …and ${products.length - 12} more at ${p.origin}`);
    lines.push("");
  }
  lines.push("## Key pages");
  lines.push(`- [Shop](${p.origin})`);
  lines.push(`- [Shipping policy](${p.origin}/policies/shipping-policy)`);
  lines.push(`- [Returns & refunds](${p.origin}/policies/refund-policy)`);
  lines.push(`- [Contact](${p.origin}/pages/contact)`);
  lines.push("");
  if (p.socials.length) {
    lines.push("## Elsewhere");
    p.socials.forEach((s) => lines.push(`- ${s}`));
    lines.push("");
  }
  lines.push(`<!-- Generated by Priority Debater · AI Commerce · ${new Date().toISOString().slice(0, 10)} -->`);
  return lines.join("\n");
}

/* ---------------- robots.txt (AI crawlers) ---------------- */

function robotsTxt(p: StoreProfile): string {
  const bots = [
    "GPTBot",
    "OAI-SearchBot",
    "ChatGPT-User",
    "ClaudeBot",
    "anthropic-ai",
    "Claude-User",
    "Google-Extended",
    "PerplexityBot",
    "Perplexity-User",
    "Amazonbot",
    "Applebot-Extended",
    "CCBot",
  ];
  const block = bots.map((b) => `User-agent: ${b}\nAllow: /`).join("\n\n");
  return [
    "# Let AI shopping agents & answer engines read your catalogue.",
    "# Many stores accidentally block these — that makes you invisible to AI buyers.",
    "",
    block,
    "",
    `Sitemap: ${p.origin}/sitemap.xml`,
    "",
  ].join("\n");
}

/* ---------------- Organization JSON-LD ---------------- */

function organizationSchema(p: StoreProfile): string {
  return jsonLd({
    "@context": "https://schema.org",
    "@type": "OnlineStore",
    name: p.name,
    url: p.origin,
    ...(p.image ? { logo: p.image, image: p.image } : {}),
    description: p.description || `${p.name} — ${p.category}.`,
    ...(p.socials.length ? { sameAs: p.socials } : {}),
  });
}

/* ---------------- Product JSON-LD ---------------- */

function productSchema(p: StoreProfile, products: ShopProduct[]): { content: string; real: boolean } {
  if (products.length) {
    // One JSON-LD block per product — put each on its matching product page.
    const blocks = products.map((pr) =>
      jsonLd({
        "@context": "https://schema.org",
        "@type": "Product",
        name: pr.title,
        ...(pr.image ? { image: pr.image } : {}),
        description: pr.description || `${pr.title} from ${p.name}.`,
        brand: { "@type": "Brand", name: pr.vendor || p.name },
        offers: {
          "@type": "Offer",
          url: pr.url,
          priceCurrency: p.currency,
          price: pr.price,
          availability: availabilityUrl(pr.available),
        },
      }),
    );
    const header = `<!-- ${products.length} products. Place each block on its matching product page (or load all via a structured-data app). -->`;
    return { real: true, content: [header, ...blocks].join("\n\n") };
  }
  return {
    real: false,
    content: jsonLd({
      "@context": "https://schema.org",
      "@type": "Product",
      name: "Your product name",
      image: "https://your-store.com/product.jpg",
      description: "One or two sentences an AI can quote about this product.",
      brand: { "@type": "Brand", name: p.name },
      offers: {
        "@type": "Offer",
        url: `${p.origin}/products/your-product`,
        priceCurrency: p.currency,
        price: "0.00",
        availability: "https://schema.org/InStock",
      },
    }),
  };
}

/* ---------------- FAQPage JSON-LD ---------------- */

function faqSchema(p: StoreProfile): string {
  const faqs = [
    {
      q: `What does ${p.name} sell?`,
      a: `${p.name} specialises in ${p.category}. ${p.description || ""}`.trim(),
    },
    {
      q: "How long does shipping take?",
      a: "Most orders ship within 1–2 business days. Add your real shipping windows and regions here so agents can answer buyers accurately.",
    },
    {
      q: "What is your return policy?",
      a: "We offer hassle-free returns within 30 days. Replace with your real terms so AI assistants quote them correctly.",
    },
    {
      q: `Why buy from ${p.name}?`,
      a: `Add 1–2 concrete differentiators (quality, guarantee, reviews) that you want AI to repeat when recommending ${p.category}.`,
    },
  ];
  return jsonLd({
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqs.map((f) => ({
      "@type": "Question",
      name: f.q,
      acceptedAnswer: { "@type": "Answer", text: f.a },
    })),
  });
}

/* ---------------- Product feed (agent-readable) ---------------- */

function productFeed(p: StoreProfile, products: ShopProduct[]): { content: string; real: boolean } {
  const items = products.length
    ? products.map((pr) => ({
        id: pr.handle || pr.title,
        title: pr.title,
        url: pr.url,
        price: pr.price,
        currency: p.currency,
        availability: pr.available ? "in_stock" : "out_of_stock",
        image: pr.image,
        category: pr.productType || p.category,
        description: pr.description,
      }))
    : [
        {
          id: "example-product",
          title: "Example product",
          url: `${p.origin}/products/example`,
          price: "0.00",
          currency: p.currency,
          availability: "in_stock",
          image: `${p.origin}/product.jpg`,
          category: p.category,
          description: "Replace with your real products, or connect your catalogue.",
        },
      ];
  return {
    real: products.length > 0,
    content: JSON.stringify(
      { store: p.name, url: p.origin, currency: p.currency, generated: new Date().toISOString(), products: items },
      null,
      2,
    ),
  };
}

/* ---------------- Buying guide (citable content) ---------------- */

function buyingGuide(p: StoreProfile): string {
  const year = new Date().getFullYear();
  return [
    `# How to choose ${p.category} (${year} buyer's guide)`,
    "",
    `A practical guide for anyone shopping for ${p.category}. Publish this on your blog — long-form guides are exactly what AI answer engines cite.`,
    "",
    "## What to look for",
    "- Criterion 1 — explain what matters and why",
    "- Criterion 2 — add a real spec or trade-off",
    "- Criterion 3 — budget vs. premium guidance",
    "",
    "## Common mistakes buyers make",
    "- Mistake 1",
    "- Mistake 2",
    "",
    `## Why shoppers choose ${p.name}`,
    `- Concrete differentiator (guarantee, materials, reviews)`,
    `- Link to your best-selling ${p.category}`,
    "",
    "## FAQ",
    `**Is ${p.category} worth it?** Answer honestly in 2–3 sentences.`,
    "",
    `*Published by ${p.name} — ${p.origin}*`,
  ].join("\n");
}

/* ---------------- off-site authority assets ---------------- */

function reviewRequestEmail(p: StoreProfile): string {
  return [
    `Subject: How was your order from ${p.name}?`,
    "",
    "Hi [First name],",
    "",
    `Thanks so much for your recent order from ${p.name} — we hope you're loving it.`,
    "",
    "Would you take 30 seconds to leave a quick review? It genuinely helps other shoppers decide —",
    "and these days it also shapes whether AI assistants (ChatGPT, Gemini, Perplexity) recommend us",
    "when people ask what to buy.",
    "",
    `👉 Leave a review: ${p.origin}`,
    "",
    "As a thank-you, here's [10% off / free shipping] on your next order: [CODE].",
    "",
    "Thank you,",
    `The ${p.name} team`,
    "",
    "— Tip: send this 5–7 days after delivery, when the product is fresh in mind.",
  ].join("\n");
}

function outreachEmail(p: StoreProfile): string {
  return [
    `Subject: ${p.name} for your "best ${p.category}" guide`,
    "",
    "Hi [Name],",
    "",
    `I'm [Your name] from ${p.name} (${p.origin}) — we make ${p.category}.`,
    "",
    `I came across your roundup of the best ${p.category} and thought we'd be a strong fit because`,
    "[ONE concrete, specific differentiator — a guarantee, a material, an award, a stat].",
    "",
    "Happy to send a sample, product details, or high-res images — whatever's easiest. Would you",
    "consider including us in the guide?",
    "",
    "Either way, love what you're doing.",
    "",
    "Thanks,",
    `[Your name], ${p.name}`,
    "",
    "— Tip: getting cited in 'best of' articles is how AI answer engines learn to recommend you.",
  ].join("\n");
}

const COMMUNITIES: Record<string, string[]> = {
  "specialty coffee equipment": ["r/espresso", "r/Coffee", "Home-Barista.com forums"],
  "beauty & skincare": ["r/SkincareAddiction", "r/30PlusSkinCare", "Beautylish community"],
  jewelry: ["r/jewelry", "PriceScope forums"],
  "apparel & fashion": ["r/femalefashionadvice", "r/malefashionadvice"],
  "health supplements": ["r/Supplements", "r/Fitness", "Examine.com"],
  "home & furniture": ["r/HomeDecorating", "r/InteriorDesign"],
  "pet products": ["r/dogs", "r/cats", "breed-specific forums"],
  "candles & fragrance": ["r/fragrance", "Basenotes forums"],
  tea: ["r/tea", "TeaChat forums"],
  "wine & spirits": ["r/wine", "r/whisky"],
  footwear: ["r/Sneakers", "r/RunningShoeGeeks"],
  "outdoor & sports gear": ["r/CampingGear", "r/Ultralight"],
  "consumer electronics": ["r/gadgets", "relevant product subreddits"],
};

function citationPlan(p: StoreProfile): string {
  const communities = COMMUNITIES[p.category] ?? [
    "the top 2–3 subreddits for your niche",
    "niche Facebook groups & Discords",
    "category-specific forums",
  ];
  const hasReviews = p.signals.reviewPlatform;
  return [
    `# Get-recommended plan for ${p.name}`,
    "",
    "AI assistants recommend stores they see trusted *elsewhere* — reviews, communities, and",
    `"best of" articles. Here's a concrete plan to build that authority for ${p.category}.`,
    "",
    "## 1. Reviews (highest impact)",
    hasReviews
      ? `- ✅ You're collecting reviews via ${hasReviews}. Now push for volume — aim for 50+ recent reviews.`
      : "- ⬜ Install a review app (Judge.me is free; Trustpilot/Okendo for more reach).",
    "- ⬜ Email past customers asking for reviews (use the Review-request email in this toolkit).",
    "- ⬜ Add AggregateRating schema so AI can quote your star rating (Product schema in this toolkit).",
    "",
    "## 2. Get cited in 'best of' guides",
    `- ⬜ Search "best ${p.category} ${new Date().getFullYear()}" and list the top 10 articles.`,
    "- ⬜ Pitch each author to include you (use the Outreach email in this toolkit).",
    "- ⬜ Offer a sample, an exclusive discount code, or unique data — make it easy to say yes.",
    "",
    "## 3. Be present where buyers discuss it",
    ...communities.map((c) => `- ⬜ ${c} — be genuinely helpful, don't spam.`),
    "",
    "## 4. Publish your own citable content",
    "- ⬜ Publish the buying guide (in this toolkit) on your blog.",
    "- ⬜ Add a comparison page: you vs the alternatives shoppers consider.",
    "",
    `*Re-run the audit in a few weeks to see your AI visibility move. — ${p.name}*`,
  ].join("\n");
}

/* ---------------- compose ---------------- */

export function buildArtifacts(p: StoreProfile, products: ShopProduct[]): GeneratedArtifact[] {
  const s = p.signals;
  const product = productSchema(p, products);
  const feed = productFeed(p, products);

  const HEAD = "Paste inside a <script type=\"application/ld+json\"> tag in your page <head>.";
  const HEAD_SHOPIFY = "Shopify: add to theme.liquid <head> (or your SEO app's JSON-LD box).";
  const HEAD_GENERIC = "WooCommerce: add via your SEO plugin's schema box, or header.php.";

  return [
    {
      id: "llms-txt",
      title: "llms.txt",
      filename: "llms.txt",
      lang: "markdown",
      why: "The manifest AI crawlers look for first — tells them what you sell and what to recommend.",
      present: s.llmsTxt,
      real: true,
      installShopify: "Host at your domain root so it resolves at /llms.txt (Shopify needs a redirect app or Cloudflare Worker — themes can't serve root files).",
      installGeneric: `Upload so it's served at ${p.origin}/llms.txt.`,
      content: llmsTxt(p, products),
    },
    {
      id: "robots-ai",
      title: "AI-crawler robots.txt",
      filename: "robots.txt",
      lang: "text",
      why: "Many stores silently block GPTBot/ClaudeBot. This explicitly invites the agents that recommend you.",
      present: false,
      real: true,
      installShopify: "Shopify: edit robots.txt.liquid in your theme and add these rules.",
      installGeneric: `Merge into your existing robots.txt at ${p.origin}/robots.txt.`,
      content: robotsTxt(p),
    },
    {
      id: "org-schema",
      title: "Organization schema",
      filename: "organization.jsonld.html",
      lang: "html",
      why: "Lets AI identify your brand as a real, citable store entity.",
      present: s.organizationJsonLd,
      real: true,
      installShopify: HEAD_SHOPIFY,
      installGeneric: `${HEAD} ${HEAD_GENERIC}`,
      content: organizationSchema(p),
    },
    {
      id: "product-schema",
      title: products.length ? `Product schema (${products.length})` : "Product schema",
      filename: "product.jsonld.html",
      lang: "html",
      why: "Machine-readable price & availability for every product so agents can compare and recommend them.",
      present: s.productJsonLd,
      real: product.real,
      installShopify: HEAD_SHOPIFY,
      installGeneric: `${HEAD} ${HEAD_GENERIC}`,
      content: product.content,
    },
    {
      id: "faq-schema",
      title: "FAQ schema",
      filename: "faq.jsonld.html",
      lang: "html",
      why: "Structured answers to buyer questions — heavily cited by AI answer engines.",
      present: s.faqJsonLd,
      real: false,
      installShopify: HEAD_SHOPIFY,
      installGeneric: `${HEAD} Edit the answers first, then ${HEAD_GENERIC.toLowerCase()}`,
      content: faqSchema(p),
    },
    {
      id: "product-feed",
      title: "Agent product feed",
      filename: "feed.json",
      lang: "json",
      why: "A clean catalogue agents can ingest to shop your store directly.",
      present: s.productFeed,
      real: feed.real,
      installShopify: "Host at /feed.json and link it from your llms.txt.",
      installGeneric: `Serve at ${p.origin}/feed.json and reference it in llms.txt.`,
      content: feed.content,
    },
    {
      id: "buying-guide",
      title: "Buying guide draft",
      filename: "buying-guide.md",
      lang: "markdown",
      why: "Long-form, citable content is what answer engines quote when recommending what to buy.",
      present: false,
      real: false,
      installShopify: "Publish as a Shopify blog post and link it in your nav + llms.txt.",
      installGeneric: "Publish on your blog and link it from your homepage + llms.txt.",
      content: buyingGuide(p),
    },
    {
      id: "get-recommended-plan",
      title: "Get-recommended plan",
      filename: "get-recommended-plan.md",
      lang: "markdown",
      kind: "outreach",
      why: "AI sources its picks off-site — reviews, communities, 'best of' lists. This is the plan to win there.",
      present: false,
      real: true,
      installShopify: "Work through it over a few weeks — reviews first, then citations.",
      installGeneric: "Work through it over a few weeks — reviews first, then citations.",
      content: citationPlan(p),
    },
    {
      id: "review-request-email",
      title: "Review-request email",
      filename: "review-request-email.txt",
      lang: "text",
      kind: "outreach",
      why: "Review volume is a top driver of AI recommendation. Send this to past customers to grow it fast.",
      present: false,
      real: true,
      installShopify: "Paste into Shopify Email or Klaviyo as a post-purchase flow (send 5–7 days after delivery).",
      installGeneric: "Send via your email tool as an automated post-purchase message.",
      content: reviewRequestEmail(p),
    },
    {
      id: "outreach-email",
      title: "Press / blogger outreach email",
      filename: "outreach-email.txt",
      lang: "text",
      kind: "outreach",
      why: "Getting cited in 'best of' roundups is how AI learns to recommend you. Pitch with this.",
      present: false,
      real: true,
      installShopify: "Personalise the [brackets] and send to authors of 'best of' guides in your category.",
      installGeneric: "Personalise the [brackets] and send to authors of 'best of' guides in your category.",
      content: outreachEmail(p),
    },
  ];
}
