"use client";

/**
 * /campaign — Stage 06 of the flow.
 *
 * Wires /api/campaign into a STATIC-ad campaign: objective, angle, budget split,
 * audience, KPIs and 4 platform-specific static creatives (on-creative headline
 * + subhead + post copy) generated from the validated idea. No video, no people,
 * no voiceover — simple image ads that sell. The "Launch ad" / "Connect account"
 * actions are genuinely not-yet-built integrations, so they surface honest demo
 * toasts.
 */

import { motion } from "framer-motion";
import { toast, Toaster } from "sonner";
import { ArrowRight, ImageIcon, Target, Wallet, Megaphone } from "lucide-react";
import { FlowNav } from "@/components/flow/FlowNav";
import { FlowTicker } from "@/components/flow/FlowTicker";
import { FlowFooter } from "@/components/flow/FlowFooter";
import { FlowStatusBanner } from "@/components/flow/FlowStatusBanner";
import { FlowGuard } from "@/components/flow/FlowGuard";
import { CopyButton } from "@/components/flow/CopyButton";
import { Label, Card } from "@/components/flow/primitives";
import { reveal, viewport } from "@/components/flow/anim";
import { useFlowPayload } from "@/lib/flow/useFlowPayload";
import { FLOW_CACHE, readFlowCache } from "@/lib/flow/useFlowIdea";
import { CAMPAIGN } from "@/lib/flow/flowMock";
import type { CampaignAd } from "@/lib/flow/types";

const adToText = (ad: CampaignAd) =>
  `${ad.concept} — ${ad.platform} (${ad.format}, ${ad.aspect})\n` +
  `On creative:\n${ad.headline}\n${ad.subhead}\n\n` +
  `Ad copy:\n${ad.adCopy.headline}\n${ad.adCopy.primary}\nCTA: ${ad.cta}`;

// Aspect-ratio box for the static creative preview.
const creativeAspect = (aspect: string) =>
  aspect === "9:16" ? "aspect-[9/16] max-w-[220px]" : aspect === "1:1" ? "aspect-square" : "aspect-video";

export default function CampaignPage() {
  const { flow, data, status, reason, regenerate } = useFlowPayload({
    endpoint: "/api/campaign",
    cacheKey: FLOW_CACHE.campaign,
    fallback: CAMPAIGN,
    buildBody: (f) => {
      const cachedBrand = readFlowCache<{ projectCode?: string }>(FLOW_CACHE.brandKit, f.input.topic);
      // Seed from what the Chamber left unresolved (§6) so the campaign answers it.
      return { ...f.input, brandName: cachedBrand?.projectCode || f.idea.brandName, debateBrief: f.debate?.brief || undefined };
    },
  });

  const fire = (msg: string, desc: string) => toast(msg, { description: desc });

  return (
    <FlowGuard stage="campaign">
    <div data-testid="campaign-page" className="bg-[#f4f4f0] min-h-screen">
      <Toaster
        position="bottom-right"
        toastOptions={{
          style: { background: "#0a0a0a", color: "#fff", border: "1px solid #fff", borderRadius: 0, fontFamily: "var(--app-font-mono)", fontSize: 12 },
        }}
      />
      <FlowNav current="campaign" subtitle="v1.0 / 2026 — Static Ads" />
      <FlowStatusBanner status={status} reason={reason} noun="ad campaign" onRegenerate={regenerate} />

      {/* Hero */}
      <section className="bg-[#0a0a0a] grid-bg-dark text-white py-16 lg:py-20 border-b-[1.5px] border-black">
        <div className="max-w-[1400px] mx-auto px-5 lg:px-8 grid lg:grid-cols-12 gap-10 items-end">
          <div className="lg:col-span-8">
            <span className="font-mono text-[10px] uppercase tracking-[0.25em] text-white/40">
              Stage 06 / Static Ad Campaign — generated by AI
            </span>
            <h1 className="mt-4 font-display text-4xl sm:text-5xl lg:text-6xl uppercase leading-[0.92]">
              Don&apos;t just post.{" "}
              <span className="bg-[#ff3b30] text-white px-2">run ads that sell.</span>
            </h1>
            <p className="mt-5 max-w-2xl text-white/60 font-body leading-relaxed">
              Scroll-stopping static ads — headline, hook and copy written for each platform from your
              idea. No filming, no actors: paste the copy, drop the creative, launch the test.
            </p>
            <div className="mt-6 border border-white/20 p-4 max-w-2xl">
              <Label><span className="text-white/40">Objective</span></Label>
              <p className="mt-2 font-body text-white/85">{data.objective}</p>
              <div className="mt-3 pt-3 border-t border-white/10">
                <Label><span className="text-[#ffd60a]">The angle</span></Label>
                <p className="mt-2 font-body text-sm text-white/70 leading-relaxed">{data.angle}</p>
              </div>
            </div>
          </div>
          <div className="lg:col-span-4 grid grid-cols-2 gap-3">
            {data.kpis.map((m) => (
              <div key={m.k} className="border border-white/20 p-3">
                <p className="font-mono text-[9px] uppercase tracking-[0.18em] text-white/40">{m.k}</p>
                <p className="font-display text-3xl mt-1" style={{ color: m.c }}>{m.v}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <main className="max-w-[1400px] mx-auto px-5 lg:px-8 py-16 lg:py-20 space-y-10">
        {/* §01 Budget & targeting */}
        <motion.section initial="hidden" whileInView="show" viewport={viewport} variants={reveal}>
          <Label>§01 / Budget &amp; targeting</Label>
          <div className="mt-4 grid lg:grid-cols-12 gap-6">
            <Card className="lg:col-span-7">
              <div className="flex items-center gap-2 mb-4">
                <Wallet size={16} />
                <span className="font-mono text-[10px] uppercase tracking-[0.18em] text-black/40">
                  {data.budget.total} test · {data.budget.daily} · {data.budget.window}
                </span>
              </div>
              <div className="space-y-3">
                {data.budgetSplit.map((b) => (
                  <div key={b.platform}>
                    <div className="flex items-center justify-between font-mono text-[11px] uppercase tracking-[0.12em] mb-1">
                      <span className="font-bold">{b.platform}</span>
                      <span className="text-black/50">{b.amount} · {b.pct}%</span>
                    </div>
                    <div className="h-3 bg-black/5 border border-black/15">
                      <div className="h-full" style={{ width: `${b.pct}%`, background: b.color }} />
                    </div>
                  </div>
                ))}
              </div>
            </Card>
            <Card className="lg:col-span-5">
              <div className="flex items-center gap-2 mb-3">
                <Target size={16} className="text-[#ff3b30]" />
                <span className="font-mono text-[10px] uppercase tracking-[0.18em] text-black/40">Audience</span>
              </div>
              <p className="text-sm text-black/70 font-body leading-relaxed">{data.audience}</p>
            </Card>
          </div>
        </motion.section>

        {/* §02 Static creatives */}
        <motion.section initial="hidden" whileInView="show" viewport={viewport} variants={reveal}>
          <div className="flex items-center justify-between flex-wrap gap-2">
            <Label>§02 / Ad creatives — image + copy</Label>
            <span className="font-mono text-[10px] uppercase tracking-[0.15em] text-black/40 flex items-center gap-1.5">
              <ImageIcon size={13} /> {data.ads.length} static creatives, one per placement
            </span>
          </div>

          <div className="mt-4 space-y-5">
            {data.ads.map((ad, i) => (
              <div key={ad.id} data-testid={`ad-card-${i}`} className="bg-white border-[1.5px] border-black shadow-hard-sm">
                {/* head */}
                <div className="flex items-center justify-between gap-4 flex-wrap px-5 py-3 border-b-[1.5px] border-black">
                  <div className="flex items-center gap-3">
                    <span className="font-mono text-[10px] uppercase tracking-[0.12em] px-2 py-1 text-white" style={{ background: ad.color }}>
                      {ad.platform}
                    </span>
                    <span className="font-display text-xl uppercase tracking-tight">{ad.concept}</span>
                  </div>
                  <div className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.12em] text-black/45">
                    <span className="border border-black/20 px-2 py-1">{ad.format}</span>
                    <span className="border border-black/20 px-2 py-1">{ad.aspect}</span>
                  </div>
                </div>

                <div className="grid lg:grid-cols-12 gap-0">
                  {/* the static creative preview — the actual image ad */}
                  <div className="lg:col-span-6 p-5 lg:border-r-[1.5px] border-black bg-[#f4f4f0] grid place-items-center">
                    <div
                      className={`${creativeAspect(ad.aspect)} w-full border-[1.5px] border-black relative overflow-hidden flex flex-col justify-between p-5`}
                      style={{ background: ad.color, color: "#fff" }}
                    >
                      <span className="font-mono text-[9px] uppercase tracking-[0.2em] opacity-70">{ad.platform}</span>
                      <div>
                        <p className="font-display uppercase leading-[0.95] text-2xl sm:text-3xl">{ad.headline}</p>
                        <p className="mt-2 font-body text-sm opacity-85 leading-snug">{ad.subhead}</p>
                      </div>
                      <span className="self-start font-mono text-[10px] uppercase tracking-[0.12em] bg-white text-black px-2.5 py-1.5">
                        {ad.cta} →
                      </span>
                    </div>
                  </div>

                  {/* the post copy that ships beside the creative */}
                  <div className="lg:col-span-6 p-5">
                    <div className="flex items-center justify-between mb-3">
                      <span className="font-mono text-[10px] uppercase tracking-[0.18em] text-[#ff3b30] flex items-center gap-1.5">
                        <Megaphone size={13} /> Ad copy
                      </span>
                      <CopyButton text={adToText(ad)} label="Copy ad" testid={`copy-ad-${i}`} />
                    </div>

                    <div className="border border-black/15 bg-white p-3">
                      <span className="font-mono text-[9px] uppercase tracking-[0.18em] text-black/40">Headline</span>
                      <p className="font-body font-bold text-base mt-1">{ad.adCopy.headline}</p>
                      <span className="font-mono text-[9px] uppercase tracking-[0.18em] text-black/40 block mt-3">Primary text</span>
                      <p className="text-sm text-black/70 font-body mt-1 leading-relaxed">{ad.adCopy.primary}</p>
                      <span className="inline-block mt-3 font-mono text-[9px] uppercase tracking-[0.12em] bg-black text-white px-2 py-1">
                        {ad.cta} →
                      </span>
                    </div>

                    <button
                      onClick={() => fire(`${ad.platform} ad launch is a demo`, "Connect your ad account to publish this creative.")}
                      data-testid={`launch-ad-${i}`}
                      className="mt-3 w-full inline-flex items-center justify-center gap-1.5 font-mono text-[10px] uppercase tracking-[0.12em] bg-black text-white px-2.5 py-2.5 hover:bg-[#0a66c2] transition-colors"
                    >
                      <Megaphone size={12} /> Launch ad
                    </button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </motion.section>

        {/* §03 Connect ad accounts */}
        <motion.section initial="hidden" whileInView="show" viewport={viewport} variants={reveal}>
          <Label>§03 / Connect ad accounts</Label>
          <Card className="mt-4">
            <p className="text-sm text-black/65 font-body leading-relaxed max-w-2xl">
              Connect a platform to push these creatives, set the budget split, and launch the test in
              one click — or export the scripts and run them manually.
            </p>
            <div className="mt-5 grid sm:grid-cols-2 lg:grid-cols-4 gap-3">
              {data.adAccounts.map((a) => (
                <button
                  key={a.name}
                  onClick={() => fire(`${a.name} is a demo`, "OAuth + ad API wiring needed to launch live campaigns.")}
                  data-testid={`connect-${a.name.split(" ")[0].toLowerCase()}`}
                  className="flex items-center justify-between border-[1.5px] border-black p-3 hover:bg-black hover:text-white transition-colors group"
                >
                  <span className="flex items-center gap-2 font-body font-bold text-sm">
                    <span className="w-2.5 h-2.5" style={{ background: a.color }} />
                    {a.name}
                  </span>
                  <span className="font-mono text-[10px] uppercase tracking-[0.15em] text-black/40 group-hover:text-white/70">
                    Connect →
                  </span>
                </button>
              ))}
            </div>
          </Card>
        </motion.section>

        {/* CTA */}
        <motion.div
          initial="hidden"
          whileInView="show"
          viewport={viewport}
          variants={reveal}
          className="bg-black text-white border-[1.5px] border-black p-8 flex flex-col sm:flex-row items-center justify-between gap-6"
        >
          <div>
            <h2 className="font-display text-3xl sm:text-4xl uppercase leading-none">
              The ad does its job. Where does the click go?
            </h2>
            <p className="mt-2 text-white/50 font-body text-sm">
              Every cut drives to one page. Let&apos;s generate the conversion page next.
            </p>
          </div>
          <a
            href="/landing-builder"
            data-testid="campaign-to-landing-cta"
            className="group shrink-0 inline-flex items-center gap-2 bg-[#ff3b30] text-white font-mono text-xs uppercase tracking-[0.2em] px-7 py-4 border-[1.5px] border-white hover:bg-white hover:text-black transition-colors"
          >
            Generate the landing page
            <ArrowRight size={16} className="group-hover:translate-x-1 transition-transform" />
          </a>
        </motion.div>
      </main>

      <FlowTicker reverse />
      <FlowFooter />
    </div>
    </FlowGuard>
  );
}
