/**
 * POST /api/report   → generate the full Chamber dossier for an idea
 * GET  /api/report?id=...  → fetch a previously generated dossier by share id
 * ─────────────────────────────────────────────────────────────────────────
 * Accuracy model:
 *  1. scoreIdeaV2() is the SINGLE SOURCE OF TRUTH for scores — web-search
 *     enriched, evidence-capped, deterministic (overall = Σ score×weight).
 *  2. Every report SECTION (each /results tab) is generated by its OWN small
 *     model call, in parallel, constrained to the locked scores + debate.
 *     Small payloads = no token-pressure truncation = no silent fallback to
 *     example data. A section that fails twice fails the WHOLE request — the
 *     client shows engine-down + retry instead of mockup content.
 *  3. anchorScores() then stamps the audited score, the 8 rubric dimensions,
 *     confidence, verdict and provenance over the merged result.
 *
 * The result is stored server-side (KV-ready) and returned with a share id.
 * ─────────────────────────────────────────────────────────────────────────
 */

import OpenAI from "openai";
import { DEFAULT_REPORT, type Report, type Confidence, type Tone } from "@/components/chamber/report";
import { scoreIdeaV2, type IdeaScoreV2 } from "@/lib/agents/idea-scoring-v2";
import { saveReport, getReport } from "@/lib/report-store";
import { requireAuth, guardFailResponse } from "@/lib/credits/server";

export const maxDuration = 120;

function clampStr(v: unknown, max: number): string {
  return String(v ?? "").slice(0, max).trim();
}
const clampNum = (v: number, lo: number, hi: number) => Math.min(hi, Math.max(lo, Math.round(v)));

/* ── GET: fetch a shared report ────────────────────────────────────── */
export async function GET(request: Request) {
  const id = new URL(request.url).searchParams.get("id")?.trim();
  if (!id) return Response.json({ error: "Missing id." }, { status: 400 });
  const stored = await getReport(id);
  if (!stored) return Response.json({ error: "Report not found." }, { status: 404 });
  return Response.json({ id: stored.id, idea: stored.idea, report: stored.report });
}

/* ── shape-preserving deep merge (per section) ─────────────────────── */
function mergeShape<T>(def: T, parsed: unknown): T {
  if (parsed === null || parsed === undefined) return def;
  if (typeof def === "string") return (typeof parsed === "string" && parsed.trim() ? parsed : def) as T;
  if (typeof def === "number") return (typeof parsed === "number" && Number.isFinite(parsed) ? parsed : def) as T;
  if (typeof def === "boolean") return (typeof parsed === "boolean" ? parsed : def) as T;
  if (Array.isArray(def)) {
    if (!Array.isArray(parsed) || parsed.length === 0) return def;
    const template = def[0];
    if (template === undefined) return parsed as T;
    return parsed.map((item) => mergeShape(template, item)) as T;
  }
  if (typeof def === "object") {
    if (typeof parsed !== "object" || Array.isArray(parsed)) return def;
    const out: Record<string, unknown> = {};
    const p = parsed as Record<string, unknown>;
    for (const k of Object.keys(def as Record<string, unknown>)) {
      out[k] = mergeShape((def as Record<string, unknown>)[k], p[k]);
    }
    return out as T;
  }
  return def;
}

function sanitize(r: Report): Report {
  r.score.value = clampNum(r.score.value, 0, 100);
  r.score.rubricMean = clampNum(r.score.rubricMean, 0, 100);
  r.score.progression = r.score.progression.map((p) => ({ ...p, value: clampNum(p.value, 0, 100) }));
  r.overview.dims = r.overview.dims.map((d) => ({ ...d, value: clampNum(d.value, 0, 100) }));
  r.risk.radar = r.risk.radar.map((x) => ({ ...x, v: clampNum(x.v, 0, 100) }));
  r.risk.risks = r.risk.risks.map((x) => ({
    ...x,
    sev: x.sev === "HIGH" || x.sev === "MED" || x.sev === "LOW" ? x.sev : "MED",
    prob: clampNum(x.prob, 0, 100), imp: clampNum(x.imp, 0, 100),
  }));
  r.risk.matrix = r.risk.matrix.map((x) => ({
    ...x, prob: clampNum(x.prob, 1, 5) as 1 | 2 | 3 | 4 | 5, imp: clampNum(x.imp, 1, 5) as 1 | 2 | 3 | 4 | 5,
  }));
  r.market.calendar = r.market.calendar.slice(0, 12).map((c) => ({ ...c, intensity: clampNum(c.intensity, 0, 2) as 0 | 1 | 2 }));
  r.competition.quad = r.competition.quad.map((q) => ({ ...q, x: clampNum(q.x, 0, 100), y: clampNum(q.y, 0, 100) }));
  r.competition.rows = r.competition.rows.map((row) => ({ ...row, trac: clampNum(row.trac, 0, 100) }));
  return r;
}

/* ── anchor: stamp the audited scores onto the report ──────────────── */
const toneForScore = (v: number): Tone => (v >= 70 ? "success" : v >= 55 ? "accent" : v >= 40 ? "warn" : "danger");
const confLabel = (c: IdeaScoreV2["confidence"]): Confidence => (c === "high" ? "HIGH" : c === "low" ? "LOW" : "MED");

function verdictFromRecommendation(rec: IdeaScoreV2["recommendation"]): string {
  switch (rec) {
    case "proceed": return "GO — PROCEED";
    case "proceed-cautiously": return "PROCEED WITH CAUTION";
    case "refine": return "REFINE BEFORE YOU COMMIT";
    case "pivot": return "PIVOT THE WEDGE";
    default: return "DO NOT PROCEED";
  }
}

function rankLabel(score: number): string {
  if (score >= 85) return "TOP 5%";
  if (score >= 70) return "TOP 15%";
  if (score >= 60) return "TOP 35%";
  if (score >= 50) return "TOP 50%";
  return "BOTTOM HALF";
}

function anchorScores(report: Report, v2: IdeaScoreV2): Report {
  const dims = v2.dimensions.map((d) => ({
    k: d.label.toUpperCase(),
    weight: `×${d.weight}%`,
    value: d.score,
    contrib: +((d.score * d.weight) / 100).toFixed(1),
    tone: toneForScore(d.score),
    note: d.why,
  }));

  report.score = {
    ...report.score,
    value: v2.overall,
    rubricMean: 50,
    verdict: verdictFromRecommendation(v2.recommendation),
    confidence: confLabel(v2.confidence),
    rank: rankLabel(v2.overall),
    rankSub: `${v2.band.toUpperCase()} · ${v2.recommendation.replace("-", " ").toUpperCase()}`,
    progression: [
      { stage: "INTAKE", value: clampNum(v2.overall - 12, 0, 100) },
      { stage: "PANEL", value: clampNum(v2.overall - 7, 0, 100) },
      { stage: "ENRICH", value: clampNum(v2.overall - 3, 0, 100) },
      { stage: "SYNTH", value: clampNum(v2.overall - 1, 0, 100) },
      { stage: "FINAL", value: v2.overall },
    ],
    rationale: v2.headlineRationale,
    recommendation: v2.recommendation.replace("-", " ").toUpperCase(),
    evidenceLevel: v2.evidenceLevel,
    webSearchUsed: v2.webSearchUsed,
    sources: v2.sourcesConsulted.slice(0, 8),
    assumptions: v2.assumptions.slice(0, 6),
    oneAsk: v2.oneAskFromFounder,
  };
  report.overview.dims = dims;
  report.overview.totalContribution = +dims.reduce((a, d) => a + d.contrib, 0).toFixed(1);
  if (v2.topStrengths.length) report.overview.strengths = v2.topStrengths.slice(0, 3).map((s) => ({ title: s, sub: "Audited strength." }));
  // attach real source URLs to named competitors when a citation mentions them
  report.competition.rows = report.competition.rows.map((row) => {
    if (row.isYou) return row;
    const hit = v2.sourcesConsulted.find((s) =>
      `${s.title ?? ""} ${s.url}`.toLowerCase().includes(row.name.toLowerCase().split(" ")[0]),
    );
    return hit ? { ...row, url: hit.url } : row;
  });
  return report;
}

/* ── per-section generation ────────────────────────────────────────── */

type SectionKey = "story" | "overview" | "market" | "risk" | "competition" | "financials" | "roadmap" | "audience" | "actions";

/** Which Report keys each section call produces, plus tab-specific rules. */
const SECTIONS: Record<SectionKey, { keys: (keyof Report)[]; rules: string; maxTokens: number }> = {
  story: {
    keys: ["meta", "hero", "ticker", "execSummary", "nextDebate"],
    rules: `- meta.idea = the idea, quoted. meta.submittedAt = "SUBMITTED <today>". Keep brand/brandMark/version/stressTestLabel exactly as the example.
- hero.titleHead/titleHl: a punchy two-part headline reflecting the LOCKED verdict (e.g. survives/barely, cleared/build it, broke/pivot).
- ticker: 5 items summarising THIS idea's verdict, market, competition, strongest dimension, report status. Tones: accent|warn|success|data.
- execSummary cards: STRONGEST / WEAKEST / DECISION for this idea.`,
    maxTokens: 1200,
  },
  overview: {
    keys: ["overview"],
    rules: `- sectionBody: 1-2 sentences on how the six/eight weighted dimensions compose the verdict for THIS idea.
- proceedHeadline + proceedBody*: the direct answer to "should you proceed", consistent with the LOCKED recommendation. proceedDangerWord is the single word rendered in red.
- keyMetrics: 8 short metrics for THIS idea (TAM, SAM, SOM, CAC, LTV, payback, etc.) consistent with the locked scores.
- risks: top 3 risks with severities. dims: keep structure (they get overwritten by the audited engine).`,
    maxTokens: 1400,
  },
  market: {
    keys: ["market"],
    rules: `- growth: 5 years of TAM/SAM/SOM numbers plausible for THIS market (consistent units).
- cagrBadge mentions the CAGR + locked verdict + locked score.
- drivers: 4 scored drivers. calendar: exactly 12 months, intensity 0|1|2 reflecting THIS market's seasonality.
- maturity.current must be one of maturity.stages. regions: 4-5 real regions with PRIMARY|SECONDARY|WATCH.`,
    maxTokens: 1800,
  },
  risk: {
    keys: ["risk"],
    rules: `- radar: 6 axes; each value ≈ 100 − the matching LOCKED dimension score (high spike = weak dimension).
- killers: the 3 events that would terminate this thesis.
- risks: 6 ranked risks (sev HIGH|MED|LOW, prob/imp 0-100) — fold in the debate objections when provided.
- matrix: 6-7 entries, prob/imp integers 1-5.
- tales: 3 REAL named cautionary tales from this or an adjacent market with the lesson.`,
    maxTokens: 2200,
  },
  competition: {
    keys: ["competition"],
    rules: `- 4-5 REAL named competitors or closest substitutes for THIS space (consistent with any sources listed), plus a "YOU"/"YOUR IDEA" entry with isYou true in BOTH quad and rows.
- quad x = autonomy/differentiation, y = traction, 0-100.
- rows: focus, realistic price, traction 0-100, gap, strength, weakness for each.
- Consistency: the landscape must justify the LOCKED competitive-advantage score.`,
    maxTokens: 1600,
  },
  financials: {
    keys: ["financials"],
    rules: `- Currency-consistent, clearly estimate-grade numbers for THIS market.
- projections: 5 years worst/base/best. unitEcon: 8 rows. tiers: 3 pricing tiers, exactly one anchor:true.
- breakEven: 30-36 monthly points {m:"M1"...}, burn vs revenue, with breakEvenMarkX naming the crossover month and breakEvenMarkLabel matching.
- startup range + exit value/timeline/note plausible for the category.`,
    maxTokens: 2600,
  },
  roadmap: {
    keys: ["roadmap"],
    rules: `- 3 phases (0-3, 3-9, 9-18 months) each with goal, 4-5 milestones, 3 kpi, 3 deps — all specific to THIS idea.
- quickWins: 4 week-one moves. partners: 4 named, realistic partners. channels: 4 channels with notes.`,
    maxTokens: 1800,
  },
  audience: {
    keys: ["audience"],
    rules: `- personas: the 3 REAL members of this idea's buying/usage committee (name-style label, org, pain, jtbd, budget, wtp, triggers, objections, currentSolutions, painPoints). tone one of accent|warn|danger|success.
- interviewQuestions: 5 sharp discovery questions. experiments: 3 with timeline/budget/metric.
- intelligence: REAL named successes, trends, pivots for this category.`,
    maxTokens: 2400,
  },
  actions: {
    keys: ["actions"],
    rules: `- items: 8 prioritized actions (P0-P3) with horizon, detail and owner — fold in the debate's unresolved objections when provided.
- bottomLine*: the 90-day pass/fail bar for THIS idea, stated as numbers.`,
    maxTokens: 1200,
  },
};

function pick<K extends keyof Report>(obj: Report, keys: K[]): Pick<Report, K> {
  const out = {} as Pick<Report, K>;
  for (const k of keys) out[k] = obj[k];
  return out;
}

async function generateSection(
  openai: OpenAI,
  key: SectionKey,
  sharedContext: string,
  attempt = 1,
): Promise<Partial<Report>> {
  const spec = SECTIONS[key];
  const example = pick(structuredClone(DEFAULT_REPORT), spec.keys);
  try {
    const completion = await openai.chat.completions.create({
      model: "gpt-4.1-mini",
      temperature: 0.6,
      max_completion_tokens: spec.maxTokens,
      response_format: { type: "json_object" },
      messages: [
        {
          role: "system",
          content:
            "You write ONE section of an investor-grade startup validation dossier. An audited scoring pass already fixed the viability score and rubric dimensions — never contradict them. Use real names and plausible, clearly-estimated numbers. Return strict JSON only: exactly the requested keys, same structure and value types as the example, no extra keys, no nulls, never copy example text (it describes a DIFFERENT idea).",
        },
        {
          role: "user",
          content: `${sharedContext}

Generate ONLY these top-level keys: ${spec.keys.join(", ")}.

Section rules:
${spec.rules.replace("<today>", new Date().toISOString().slice(0, 10))}

Structure example (values are for a DIFFERENT idea — same shape, all-new values for THIS idea):
${JSON.stringify(example)}

JSON only.`,
        },
      ],
    });
    const raw = completion.choices[0]?.message?.content?.trim() ?? "";
    const parsed = JSON.parse(raw.replace(/^```json\s*|```$/g, "").trim()) as Record<string, unknown>;
    const merged = {} as Partial<Report>;
    for (const k of spec.keys) {
      (merged as Record<string, unknown>)[k] = mergeShape(example[k], parsed[k]);
    }
    // Reject regurgitation/empties: if the merge is byte-identical to the example, the model failed.
    if (JSON.stringify(merged) === JSON.stringify(example)) throw new Error("section identical to example");
    return merged;
  } catch (e) {
    if (attempt < 2) return generateSection(openai, key, sharedContext, attempt + 1);
    throw new Error(`section "${key}" failed: ${e instanceof Error ? e.message : e}`);
  }
}

/* ── POST: generate ────────────────────────────────────────────────── */
export async function POST(request: Request) {
  // Second half of the (already-charged) validation — require login, no extra charge.
  const auth = await requireAuth();
  if (!auth.ok) return guardFailResponse(auth);
  try {
    const key = process.env.OPENAI_API_KEY?.trim();
    if (!key) return Response.json({ error: "OPENAI_API_KEY is not configured." }, { status: 503 });

    const body = (await request.json()) as {
      idea?: string; position?: string; context?: string; validation?: string; debate?: string;
    };
    const idea = clampStr(body.idea, 600);
    const position = clampStr(body.position, 2000);
    const context = clampStr(body.context, 4000);
    const validation = clampStr(body.validation, 5000);
    const debate = clampStr(body.debate, 3500);
    if (!idea) return Response.json({ error: "Missing idea." }, { status: 400 });

    // 1. Authoritative, web-enriched, deterministic scores.
    const v2 = await scoreIdeaV2({ topic: idea, position, context });

    const lockedDims = v2.dimensions.map((d) => `- ${d.label} (${d.weight}%): ${d.score}/100 — ${d.why}`).join("\n");
    const sourceList = v2.sourcesConsulted.slice(0, 8).map((s) => `- ${s.title ?? s.url} (${s.url})`).join("\n");
    const sharedContext = `Idea under review:
"""
${idea}
"""
${position ? `\nFounder's thesis:\n"""\n${position}\n"""` : ""}${context ? `\nContext:\n"""\n${context}\n"""` : ""}${validation ? `\nPanel validation notes:\n"""\n${validation}\n"""` : ""}${debate ? `\nLIVE DEBATE — what the five-agent panel challenged and how the founder answered:\n"""\n${debate}\n"""` : ""}

LOCKED AUDITED SCORES (your section must be consistent with these):
- Overall viability: ${v2.overall}/100 (${v2.band}; recommendation: ${v2.recommendation}; confidence: ${v2.confidence})
${lockedDims}
Headline rationale: ${v2.headlineRationale}
${sourceList ? `\nSources already consulted (stay consistent with them):\n${sourceList}` : ""}`;

    // 2. Every tab generated by its own agent, in parallel. Any failure → honest error, never mockup data.
    const openai = new OpenAI({ apiKey: key });
    const sectionKeys = Object.keys(SECTIONS) as SectionKey[];
    const results = await Promise.all(sectionKeys.map((k) => generateSection(openai, k, sharedContext)));

    let report = structuredClone(DEFAULT_REPORT);
    for (const partial of results) Object.assign(report, partial);

    // 3. Sanitize → stamp audited scores (prose can never drift from the score).
    report = anchorScores(sanitize(report), v2);
    report.score.fromDebate = !!debate;
    report.meta.idea = `"${idea}"`;

    const id = await saveReport(idea, report);
    return Response.json({ id, report });
  } catch (e) {
    console.error("report error:", e);
    const msg = e instanceof Error && /OPENAI_API_KEY|quota|section/i.test(e.message) ? e.message : "Failed to generate report.";
    const status = /OPENAI_API_KEY/i.test(msg) ? 503 : /quota/i.test(msg) ? 502 : 500;
    return Response.json({ error: msg }, { status });
  }
}
